#!/usr/bin/env python3
"""
Bakes the Fraunces "D." into scripts/gen-assets/glyphs.js as outline data.

    python3 -m pip install fonttools brotli uharfbuzz
    python3 scripts/gen-assets/extract-glyphs.py
    npm run gen:assets

The icon is set in the app's own display face, but it must not depend on that
face at render time: an SVG <text> is whatever the rasterising machine does
with it (see mark.js), and a favicon cannot carry a font subset. So this reads
the VENDORED woff2 once, pins the variable axes to one instance, shapes the
text with HarfBuzz (the shaper Chromium uses, so kerning matches the wordmark
the app sets live), and writes the resulting outlines as plain path data.
Everything downstream is geometry again, byte-identical on every machine.

Run it only when the vendored font or the instance below changes;
brandAssets.test.js fails if the font's hash no longer matches the one
recorded in glyphs.js. It is Python because fontTools is the reference
implementation of variable-font instancing; nothing in CI or `gen:assets`
needs it.
"""

import hashlib
import io
import json
import pathlib
import subprocess

import uharfbuzz as hb
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

ROOT = pathlib.Path(__file__).resolve().parents[2]
FONT = pathlib.Path('public/fonts/fraunces/fraunces-latin-normal-300-900.woff2')
OUT = pathlib.Path('scripts/gen-assets/glyphs.js')

TEXT = 'D.'
# Two instances, because that is what the optical-size axis is for.
#
# `display` is every launcher icon and launch screen: opsz 144 is the cut the
# app's headlines get, and wght 800 keeps its hairlines at ~1.6% of the cap
# height, which still lands on a pixel on any launcher density shipping today.
#
# `small` is the favicon only. At 16px the display cut's hairlines are a fifth
# of a pixel and the D falls apart into a stem and an arc; opsz 9 is Fraunces'
# own small-size design, with sturdier horizontals and serifs, and wght 900
# buys back a little more.
CUTS = {
    'display': {'opsz': 144, 'wght': 800},
    'small': {'opsz': 9, 'wght': 900},
}
# Height of the normalised box, in the same 0-100 units mark.js always used.
EM = 100


def num(n):
    """Two decimals is 0.05px on a 1024 icon; strip the zeros it does not need."""
    s = f'{n:.2f}'.rstrip('0').rstrip('.')
    return '0' if s == '-0' else s


def extract(raw, axes):
    font = instancer.instantiateVariableFont(TTFont(io.BytesIO(raw)), axes)
    glyph_set = font.getGlyphSet()
    order = font.getGlyphOrder()

    buf = io.BytesIO()
    font.flavor = None
    font.save(buf)
    hb_font = hb.Font(hb.Face(buf.getvalue()))
    shaped = hb.Buffer()
    shaped.add_str(TEXT)
    shaped.guess_segment_properties()
    hb.shape(hb_font, shaped)

    placed = []
    pen_x = 0
    for info, pos in zip(shaped.glyph_infos, shaped.glyph_positions):
        placed.append((order[info.codepoint], pen_x + pos.x_offset, pos.y_offset))
        pen_x += pos.x_advance
    if len(placed) != 2:
        raise SystemExit(f'expected 2 glyphs for {TEXT!r}, got {placed}')

    boxes = []
    for name, dx, dy in placed:
        bp = BoundsPen(glyph_set)
        glyph_set[name].draw(bp)
        x0, y0, x1, y1 = bp.bounds
        boxes.append((x0 + dx, y0 + dy, x1 + dx, y1 + dy))
    x_min = min(b[0] for b in boxes)
    y_min = min(b[1] for b in boxes)
    x_max = max(b[2] for b in boxes)
    y_max = max(b[3] for b in boxes)
    scale = EM / (y_max - y_min)

    def outline(name, dx, dy):
        # Font space is y-up from the baseline; SVG is y-down from the top-left
        # of the box, so flip and shift in one affine.
        svg = SVGPathPen(glyph_set, ntos=num)
        glyph_set[name].draw(
            TransformPen(svg, (scale, 0, 0, -scale, (dx - x_min) * scale, (y_max - dy) * scale))
        )
        return svg.getCommands()

    (letter, *_), (period, *_) = placed
    return {
        'axes': axes,
        'width': float(num((x_max - x_min) * scale)),
        'height': EM,
        'letter': outline(letter, *placed[0][1:]),
        'period': outline(period, *placed[1][1:]),
    }


def main():
    raw = (ROOT / FONT).read_bytes()
    glyphs = {
        'source': {
            'file': FONT.as_posix(),
            'sha256': hashlib.sha256(raw).hexdigest(),
            'text': TEXT,
        },
        **{cut: extract(raw, axes) for cut, axes in CUTS.items()},
    }

    body = json.dumps(glyphs, indent=2).replace('"', "'")
    (ROOT / OUT).write_text(
        '// Generated by scripts/gen-assets/extract-glyphs.py. Do not hand-edit:\n'
        '// change the font or the instance there and re-run it.\n'
        '//\n'
        '// The Fraunces "D." as outlines, one set per optical cut, each normalised so\n'
        '// the pair spans x 0..width, y 0..height (y down). See mark.js.\n'
        f'export const GLYPHS = {body};\n',
        encoding='utf-8',
    )
    # So a re-run with nothing changed leaves no diff.
    subprocess.run(['npx', 'prettier', '--write', OUT.as_posix()], cwd=ROOT, check=True)
    for cut in CUTS:
        g = glyphs[cut]
        print(f'  {OUT.as_posix():<30} {cut:<8} {g["axes"]}  {g["width"]} x {g["height"]}')


main()
