// Pure helpers for capture.mjs, split out so lib.test.js can hold them.

const ALL_TARGETS = ['iphone', 'ipad', 'play'];

/**
 * @param {string[]} argv
 * @returns {{ targets: string[], scenes: string[] | null, skipBuild: boolean, out: string }}
 */
export function parseArgs(argv) {
  const opts = { targets: ALL_TARGETS, scenes: null, skipBuild: false, out: 'store-screenshots' };
  for (let i = 0; i < argv.length; i++) {
    const [flag, inline] = argv[i].split('=');
    const value = () => inline ?? argv[++i];
    if (flag === '--targets') opts.targets = value().split(',').filter(Boolean);
    else if (flag === '--scenes') opts.scenes = value().split(',').filter(Boolean);
    else if (flag === '--skip-build') opts.skipBuild = true;
    else if (flag === '--out') opts.out = value();
    else throw new Error(`unknown flag ${argv[i]}`);
  }
  const bad = opts.targets.filter((t) => !ALL_TARGETS.includes(t));
  if (bad.length)
    throw new Error(`unknown target ${bad.join(', ')} (use ${ALL_TARGETS.join(', ')})`);
  return opts;
}

export const DRIVER_MARK = 'data-shots-driver';

/**
 * Puts the driver into a copied bundle's index.html, just before </body>.
 * Idempotent: a second call replaces the first injection rather than
 * stacking two drivers.
 */
export function injectDriver(html, driverSource, cfg) {
  const clean = html.replace(new RegExp(`<script ${DRIVER_MARK}>[\\s\\S]*?</script>`, 'g'), '');
  // `</script` inside the source would end the tag early.
  const body = `window.__SHOTS__ = ${JSON.stringify(cfg)};\n${driverSource}`.replace(
    /<\/script/gi,
    '<\\/script'
  );
  if (!clean.includes('</body>')) throw new Error('bundle index.html has no </body>');
  return clean.replace('</body>', `<script ${DRIVER_MARK}>${body}</script></body>`);
}

/**
 * REPORT.md: what was produced, what was skipped and why, and the plan's
 * export checklist with the boxes this run can honestly tick.
 */
export function reportMarkdown({ rows, notes, scenes, targets, graphic }) {
  const ok = (r) => r.status === 'ok';
  const shots = rows.filter((r) => r.file !== graphic.file);
  const allSized = shots.length > 0 && shots.every((r) => r.status !== 'failed');
  const box = (done, text) => `- [${done ? 'x' : ' '}] ${text}`;
  const lines = [
    '# Store screenshots — capture report',
    '',
    'Generated by `npm run screenshots:capture` from the native release-candidate',
    'apps (iOS Release build in the Simulator; Android APK on an emulator or phone),',
    'seeded with `scripts/dev/screenshot-seed.js`. See',
    '`docs/store-metadata/store-screenshot-plan.md`.',
    '',
    '| Target | File | Status | Detail |',
    '| --- | --- | --- | --- |',
    ...rows.map(
      (r) =>
        `| ${targets[r.target]?.label ?? r.target} | \`${r.file}\` | ${r.status} | ${r.detail.replace(/\|/g, '\\|')} |`
    ),
    '',
  ];
  if (notes.length) lines.push(...notes.map((n) => `> ${n}`), '');
  lines.push(
    '## Alt text (Google Play)',
    '',
    ...scenes.filter((s) => !s.skip).map((s) => `- \`${s.file}\`: ${s.alt}`),
    `- \`${graphic.file}\`: ${graphic.alt}`,
    '',
    '## Export and submission checks',
    '',
    box(
      false,
      'All Apple and Android captures show the submitted build and the same feature claims — **owner review** (scene 5 is captured by hand from the fictional account).'
    ),
    box(
      shots.some(ok),
      'The first three images prioritise real UI and the core learning experience.'
    ),
    box(
      false,
      'No screenshot contains personal data, debug controls, ads, push, Premium or an unshipped feature — **owner review** (the run used a fictional guest seed and the store-build flags).'
    ),
    box(
      shots.some(ok),
      'Every overlay is English (U.S.) and occupies no more than 20% of the image (the headline band is 17%).'
    ),
    box(
      allSized,
      'PNG exports have no alpha channel; nothing is stretched (captures are scaled proportionally).'
    ),
    box(
      allSized,
      'Exports are exactly 1320×2868 (iPhone), 2064×2752 (iPad), 1080×1920 (Play) and 1024×500 (feature graphic) — checked from each file’s own bytes.'
    ),
    box(
      false,
      'Each Play screenshot and the feature graphic receives the alt text above — **owner, in Play Console**.'
    ),
    box(
      false,
      'The captures still match `app-store-listing.md` and `google-play-listing.md` — **owner review**.'
    ),
    ''
  );
  return lines.join('\n');
}
